module urcl_init_ir
   use include, only: BIG, SMALL
   use ir, only: full_ir, ir_create_type, ir_procedure, ir_subtype, HINT_INT, full_ir_type, ir_var

   implicit none (type, external)

   enum, bind(c)
      ! data movement instructions
      enumerator :: ASM_MOV = 1
      enumerator :: ASM_LOD
      enumerator :: ASM_STR
      enumerator :: ASM_LLOD
      enumerator :: ASM_LSTR
      enumerator :: ASM_CPY
      enumerator :: ASM_PSH
      enumerator :: ASM_POP

      enumerator :: ASM_LODA ! loading argument from stack

      ! arithmetic instructions
      enumerator :: ASM_ADD
      enumerator :: ASM_SUB
      enumerator :: ASM_ABS
      enumerator :: ASM_MLT
      enumerator :: ASM_UMLT
      enumerator :: ASM_SUMLT
      enumerator :: ASM_DIV
      enumerator :: ASM_SDIV
      enumerator :: ASM_MOD

      ! logical instructions
      enumerator :: ASM_OR
      enumerator :: ASM_NOR
      enumerator :: ASM_AND
      enumerator :: ASM_NAND
      enumerator :: ASM_XOR
      enumerator :: ASM_XNOR

      ! shifting instructions
      enumerator :: ASM_BSL
      enumerator :: ASM_BSR
      enumerator :: ASM_BSS

      ! branching instructions
      enumerator :: ASM_CAL
      enumerator :: ASM_RET
      enumerator :: ASM_JMP
      enumerator :: ASM_BGE
      enumerator :: ASM_BRG
      enumerator :: ASM_BLE
      enumerator :: ASM_BRL
      enumerator :: ASM_SBGE
      enumerator :: ASM_SBRG
      enumerator :: ASM_SBLE
      enumerator :: ASM_SBRL
      enumerator :: ASM_BRE
      enumerator :: ASM_BNE
      enumerator :: ASM_BRN
      enumerator :: ASM_BRP
      enumerator :: ASM_BOD
      enumerator :: ASM_BEV
      enumerator :: ASM_BRC
      enumerator :: ASM_BNC

      ! set instructions
      enumerator :: ASM_SETE
      enumerator :: ASM_SETNE
      enumerator :: ASM_SETGE
      enumerator :: ASM_SETG
      enumerator :: ASM_SETLE
      enumerator :: ASM_SETL
      enumerator :: ASM_SSETGE
      enumerator :: ASM_SSETG
      enumerator :: ASM_SSETLE
      enumerator :: ASM_SSETL
      enumerator :: ASM_SETC
      enumerator :: ASM_SETNC

      ! io instructions
      enumerator :: ASM_IN
      enumerator :: ASM_OUT

      ! completness instructions
      ! (these aren't generated by compiler passes, but could be used in inline assembly)
      ! (we don't want to destroy peoples' inline assembly)
      enumerator :: ASM_DW
      enumerator :: ASM_NOP
      enumerator :: ASM_HLT
      enumerator :: ASM_IMM
      enumerator :: ASM_NOT
      enumerator :: ASM_INC
      enumerator :: ASM_DEC
      enumerator :: ASM_BRZ
      enumerator :: ASM_BNZ
      enumerator :: ASM_NEG
   end enum
contains
   subroutine setup_builtin(bits, intermediate)
      integer(SMALL), value, intent(in) :: bits
      type(full_ir), intent(inout) :: intermediate

      class(*), allocatable :: tmp

      type(full_ir_type) :: word_type
      integer(BIG) :: a, b, c

      tmp = ir_create_type('\word', bits, HINT_INT)
      call intermediate%types%move_push(tmp)
      word_type = full_ir_type(type = intermediate%types%size)

      tmp = ir_create_type('\addr', bits, HINT_INT)
      call intermediate%types%move_push(tmp)

      tmp = ir_var('a', word_type)
      call intermediate%vars%move_push(tmp)
      a = intermediate%vars%size

      tmp = ir_var('b', word_type)
      call intermediate%vars%move_push(tmp)
      b = intermediate%vars%size

      tmp = ir_var('c', word_type)
      call intermediate%vars%move_push(tmp)
      c = intermediate%vars%size

      ! data movement instructions
      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.mov', &
         arguments = [b])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         lzero_illegal = .true., &
         return_type = word_type, &
         name = 'asm.lod', &
         arguments = [b])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         lzero_illegal = .true., &
         name = 'asm.str', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         commutative = .true., &
         name = 'asm.llod', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         commutative = .true., &
         name = 'asm.lstr', &
         arguments = [a, b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         lzero_illegal = .true., &
         rzero_illegal = .true., &
         name = 'asm.cpy', &
         arguments = [a, b])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         name = 'asm.psh', &
         arguments = [a])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         return_type = word_type, &
         name = 'asm.pop')
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         return_type = word_type, &
         name = 'asm.loda', &
         arguments = [b])
      call intermediate%procedures%move_push(tmp)

      ! arithmetic instructions
      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         zero_identity = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.add', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         zero_identity = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.sub', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         lreduce_0_0 = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.abs', &
         arguments = [b])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         one_identity = .true., &
         lreduce_0_0 = .true., &
         rreduce_0_0 = .true., &
         reduce_add = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.mlt', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         lreduce_0_0 = .true., &
         rreduce_0_0 = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.umlt', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         lreduce_0_0 = .true., &
         rreduce_0_0 = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.sumlt', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         one_identity = .true., &
         lreduce_0_0 = .true., &
         rzero_illegal = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.div', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         one_identity = .true., &
         lreduce_0_0 = .true., &
         rzero_illegal = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.sdiv', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         lreduce_0_0 = .true., &
         rzero_illegal = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.mod', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         zero_identity = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.or', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.nor', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         lreduce_0_0 = .true., &
         rreduce_0_0 = .true., &
         rzero_illegal = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.and', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.nand', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         associative = .true., &
         zero_identity = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.xor', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         commutative = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.xnor', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      ! shifting instructions
      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         zero_identity = .true., &
         lreduce_0_0 = .true., &
         reduce_add = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.bsl', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         zero_identity = .true., &
         lreduce_0_0 = .true., &
         reduce_add = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.bsr', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         pure = .true., &
         simple = .true., &
         zero_identity = .true., &
         lreduce_0_0 = .true., &
         reduce_add = .true., &
         evaluatable = .true., &
         return_type = word_type, &
         name = 'asm.bss', &
         arguments = [b, c])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         lzero_illegal = .true., &
         name = 'asm.cal', &
         arguments = [b])
      call intermediate%procedures%move_push(tmp)

      tmp = ir_procedure( &
         fundamental = .true., &
         variadic = .true., &
         name = 'asm.ret')
      call intermediate%procedures%move_push(tmp)
   end subroutine
end module
