name = "urclfortran"
version = "0.1.0"

[build]
auto-executables = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"