name = "urclfortran"
version = "0.1.0"
license = "license"
author = "Oliver Hines"
maintainer = "olivermhines@gmail.com"
copyright = "Copyright 2025, Oliver Hines"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

