name = "urclfortran"
version = "0.1.0"

[build]
auto-executables = true
auto-tests = false
auto-examples = false
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[features]
debug.gfortran.flags = "-std=f2018 -fall-intrinsics -O0 -g -Wimplicit-interface -Wall -Wextra -fcheck=all -pedantic -fbacktrace -ffpe-trap=invalid,zero,overflow -finit-real=snan -finit-integer=-99999999 -DDEBUG"
debug.ifort.flags = "-O0 -g -gen-interface -warn all -traceback -check all -ftrapuv -debug all -DDEBUG"
debug.ifx.flags = "-O0 -g -gen-interface -warn all -traceback -check all -ftrapuv -debug all -DDEBUG"
debug.flang.flags = "-std=f2018 -O0 -g -DDEBUG -pedantic"
debug.lfortran.flags = "-O0 -g -Wall -Wextra -DDEBUG"

release.flags = "-O3"
release.gfortran.flags = "-O3 -ffast-math -fstack-arrays -march=native"
release.flang.flags = "-O3 -ffast-math -fstack-arrays -march=native -flto"

[profiles]
debug = ["debug"]
release = ["release"]
